from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from .. import models, schemas, database
from ..services.firebase_service import create_live_trip_node # (Keep your old service file!)

router = APIRouter(
    prefix="/api/driver",
    tags=["driver"]
)

@router.post("/start-trip", response_model=schemas.TripResponse)
def start_trip(request: schemas.TripStartRequest, db: Session = Depends(database.get_db)):
    
    # 1. Create Trip in Postgres
    new_trip = models.Trip(
        bus_id=request.bus_id,
        route_id=request.route_id,
        driver_id=request.driver_id,
        status="live"
    )
    db.add(new_trip)
    db.commit()
    db.refresh(new_trip) # Get the ID generated by DB

    # 2. Create Node in Firebase
    firebase_success = create_live_trip_node(
        trip_id=new_trip.id,
        bus_id=request.bus_id,
        driver_id=request.driver_id,
        route_id=request.route_id
    )

    if not firebase_success:
        # Optional: You might want to log this error
        print("Warning: Firebase sync failed")

    return {
        "message": "Trip started successfully",
        "trip_id": new_trip.id,
        "status": "live"
    }